### ISSUE TITLE
Just saying thanks!

### ISSUE THREAD

**Issue by IonicaBizau** [remy/snap#1]
@remy Thank you so much for building this. I started to build something similar and I gave up. 😁

I love this project so much! 🌟 
From a quick testing I saw it just works. 🎉

**Comment by remy** [comment]
😁🎈 thank you for taking a moment to say so ❤️

**Comment by IonicaBizau** [comment]
Oh, and I struggled with `wget` too: https://unix.stackexchange.com/q/318795/45370

Btw, you can post an answer if you like. 😄
